/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as AgentNotFoundRouteImport } from './routes/agent-not-found'
import { Route as AgentRouteImport } from './routes/_agent'
import { Route as R403RouteImport } from './routes/403'
import { Route as AgentAuthenticatedRouteImport } from './routes/_agent/_authenticated'
import { Route as AgentAuthenticatedIndexRouteImport } from './routes/_agent/_authenticated/index'
import { Route as AgentAuthenticatedUserAuthenticatedRouteImport } from './routes/_agent/_authenticated/user/_authenticated'
import { Route as AgentAuthenticatedStaffAuthenticatedRouteImport } from './routes/_agent/_authenticated/staff/_authenticated'
import { Route as AgentAuthenticatedOwnerAuthenticatedRouteImport } from './routes/_agent/_authenticated/owner/_authenticated'
import { Route as AgentAuthenticatedManagerAuthenticatedRouteImport } from './routes/_agent/_authenticated/manager/_authenticated'
import { Route as AgentAuthenticatedUserAuthenticatedIndexRouteImport } from './routes/_agent/_authenticated/user/_authenticated/index'
import { Route as AgentAuthenticatedStaffAuthenticatedIndexRouteImport } from './routes/_agent/_authenticated/staff/_authenticated/index'
import { Route as AgentAuthenticatedOwnerAuthenticatedIndexRouteImport } from './routes/_agent/_authenticated/owner/_authenticated/index'
import { Route as AgentAuthenticatedManagerAuthenticatedIndexRouteImport } from './routes/_agent/_authenticated/manager/_authenticated/index'
import { Route as AgentAuthenticatedUserAuthenticatedTopupRouteImport } from './routes/_agent/_authenticated/user/_authenticated/topup'
import { Route as AgentAuthenticatedUserAuthenticatedOrderRouteImport } from './routes/_agent/_authenticated/user/_authenticated/order'
import { Route as AgentAuthenticatedUserAuthenticatedLoyaltyRouteImport } from './routes/_agent/_authenticated/user/_authenticated/loyalty'
import { Route as AgentAuthenticatedUserAuthenticatedDeviceRouteImport } from './routes/_agent/_authenticated/user/_authenticated/device'
import { Route as AgentAuthenticatedStaffAuthenticatedStationsRouteImport } from './routes/_agent/_authenticated/staff/_authenticated/stations'
import { Route as AgentAuthenticatedStaffAuthenticatedOrderRouteImport } from './routes/_agent/_authenticated/staff/_authenticated/order'
import { Route as AgentAuthenticatedStaffAuthenticatedAccountsRouteImport } from './routes/_agent/_authenticated/staff/_authenticated/accounts'
import { Route as AgentAuthenticatedOwnerAuthenticatedSystemRouteImport } from './routes/_agent/_authenticated/owner/_authenticated/system'
import { Route as AgentAuthenticatedOwnerAuthenticatedPolicyRouteImport } from './routes/_agent/_authenticated/owner/_authenticated/policy'
import { Route as AgentAuthenticatedOwnerAuthenticatedGeneralRouteImport } from './routes/_agent/_authenticated/owner/_authenticated/general'
import { Route as AgentAuthenticatedOwnerAuthenticatedFinanceRouteImport } from './routes/_agent/_authenticated/owner/_authenticated/finance'
import { Route as AgentAuthenticatedOwnerAuthenticatedDiaryRouteImport } from './routes/_agent/_authenticated/owner/_authenticated/diary'
import { Route as AgentAuthenticatedManagerAuthenticatedStationsRouteImport } from './routes/_agent/_authenticated/manager/_authenticated/stations'
import { Route as AgentAuthenticatedManagerAuthenticatedStaffsRouteImport } from './routes/_agent/_authenticated/manager/_authenticated/staffs'
import { Route as AgentAuthenticatedManagerAuthenticatedLoyaltyRouteImport } from './routes/_agent/_authenticated/manager/_authenticated/loyalty'
import { Route as AgentAuthenticatedManagerAuthenticatedIqrRouteImport } from './routes/_agent/_authenticated/manager/_authenticated/iqr'
import { Route as AgentAuthenticatedManagerAuthenticatedGamesRouteImport } from './routes/_agent/_authenticated/manager/_authenticated/games'

const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentNotFoundRoute = AgentNotFoundRouteImport.update({
  id: '/agent-not-found',
  path: '/agent-not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/_agent',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAuthenticatedRoute = AgentAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AgentRoute,
} as any)
const AgentAuthenticatedIndexRoute = AgentAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentAuthenticatedRoute,
} as any)
const AgentAuthenticatedUserAuthenticatedRoute =
  AgentAuthenticatedUserAuthenticatedRouteImport.update({
    id: '/user/_authenticated',
    path: '/user',
    getParentRoute: () => AgentAuthenticatedRoute,
  } as any)
const AgentAuthenticatedStaffAuthenticatedRoute =
  AgentAuthenticatedStaffAuthenticatedRouteImport.update({
    id: '/staff/_authenticated',
    path: '/staff',
    getParentRoute: () => AgentAuthenticatedRoute,
  } as any)
const AgentAuthenticatedOwnerAuthenticatedRoute =
  AgentAuthenticatedOwnerAuthenticatedRouteImport.update({
    id: '/owner/_authenticated',
    path: '/owner',
    getParentRoute: () => AgentAuthenticatedRoute,
  } as any)
const AgentAuthenticatedManagerAuthenticatedRoute =
  AgentAuthenticatedManagerAuthenticatedRouteImport.update({
    id: '/manager/_authenticated',
    path: '/manager',
    getParentRoute: () => AgentAuthenticatedRoute,
  } as any)
const AgentAuthenticatedUserAuthenticatedIndexRoute =
  AgentAuthenticatedUserAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AgentAuthenticatedUserAuthenticatedRoute,
  } as any)
const AgentAuthenticatedStaffAuthenticatedIndexRoute =
  AgentAuthenticatedStaffAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AgentAuthenticatedStaffAuthenticatedRoute,
  } as any)
const AgentAuthenticatedOwnerAuthenticatedIndexRoute =
  AgentAuthenticatedOwnerAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AgentAuthenticatedOwnerAuthenticatedRoute,
  } as any)
const AgentAuthenticatedManagerAuthenticatedIndexRoute =
  AgentAuthenticatedManagerAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AgentAuthenticatedManagerAuthenticatedRoute,
  } as any)
const AgentAuthenticatedUserAuthenticatedTopupRoute =
  AgentAuthenticatedUserAuthenticatedTopupRouteImport.update({
    id: '/topup',
    path: '/topup',
    getParentRoute: () => AgentAuthenticatedUserAuthenticatedRoute,
  } as any)
const AgentAuthenticatedUserAuthenticatedOrderRoute =
  AgentAuthenticatedUserAuthenticatedOrderRouteImport.update({
    id: '/order',
    path: '/order',
    getParentRoute: () => AgentAuthenticatedUserAuthenticatedRoute,
  } as any)
const AgentAuthenticatedUserAuthenticatedLoyaltyRoute =
  AgentAuthenticatedUserAuthenticatedLoyaltyRouteImport.update({
    id: '/loyalty',
    path: '/loyalty',
    getParentRoute: () => AgentAuthenticatedUserAuthenticatedRoute,
  } as any)
const AgentAuthenticatedUserAuthenticatedDeviceRoute =
  AgentAuthenticatedUserAuthenticatedDeviceRouteImport.update({
    id: '/device',
    path: '/device',
    getParentRoute: () => AgentAuthenticatedUserAuthenticatedRoute,
  } as any)
const AgentAuthenticatedStaffAuthenticatedStationsRoute =
  AgentAuthenticatedStaffAuthenticatedStationsRouteImport.update({
    id: '/stations',
    path: '/stations',
    getParentRoute: () => AgentAuthenticatedStaffAuthenticatedRoute,
  } as any)
const AgentAuthenticatedStaffAuthenticatedOrderRoute =
  AgentAuthenticatedStaffAuthenticatedOrderRouteImport.update({
    id: '/order',
    path: '/order',
    getParentRoute: () => AgentAuthenticatedStaffAuthenticatedRoute,
  } as any)
const AgentAuthenticatedStaffAuthenticatedAccountsRoute =
  AgentAuthenticatedStaffAuthenticatedAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AgentAuthenticatedStaffAuthenticatedRoute,
  } as any)
const AgentAuthenticatedOwnerAuthenticatedSystemRoute =
  AgentAuthenticatedOwnerAuthenticatedSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => AgentAuthenticatedOwnerAuthenticatedRoute,
  } as any)
const AgentAuthenticatedOwnerAuthenticatedPolicyRoute =
  AgentAuthenticatedOwnerAuthenticatedPolicyRouteImport.update({
    id: '/policy',
    path: '/policy',
    getParentRoute: () => AgentAuthenticatedOwnerAuthenticatedRoute,
  } as any)
const AgentAuthenticatedOwnerAuthenticatedGeneralRoute =
  AgentAuthenticatedOwnerAuthenticatedGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AgentAuthenticatedOwnerAuthenticatedRoute,
  } as any)
const AgentAuthenticatedOwnerAuthenticatedFinanceRoute =
  AgentAuthenticatedOwnerAuthenticatedFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AgentAuthenticatedOwnerAuthenticatedRoute,
  } as any)
const AgentAuthenticatedOwnerAuthenticatedDiaryRoute =
  AgentAuthenticatedOwnerAuthenticatedDiaryRouteImport.update({
    id: '/diary',
    path: '/diary',
    getParentRoute: () => AgentAuthenticatedOwnerAuthenticatedRoute,
  } as any)
const AgentAuthenticatedManagerAuthenticatedStationsRoute =
  AgentAuthenticatedManagerAuthenticatedStationsRouteImport.update({
    id: '/stations',
    path: '/stations',
    getParentRoute: () => AgentAuthenticatedManagerAuthenticatedRoute,
  } as any)
const AgentAuthenticatedManagerAuthenticatedStaffsRoute =
  AgentAuthenticatedManagerAuthenticatedStaffsRouteImport.update({
    id: '/staffs',
    path: '/staffs',
    getParentRoute: () => AgentAuthenticatedManagerAuthenticatedRoute,
  } as any)
const AgentAuthenticatedManagerAuthenticatedLoyaltyRoute =
  AgentAuthenticatedManagerAuthenticatedLoyaltyRouteImport.update({
    id: '/loyalty',
    path: '/loyalty',
    getParentRoute: () => AgentAuthenticatedManagerAuthenticatedRoute,
  } as any)
const AgentAuthenticatedManagerAuthenticatedIqrRoute =
  AgentAuthenticatedManagerAuthenticatedIqrRouteImport.update({
    id: '/iqr',
    path: '/iqr',
    getParentRoute: () => AgentAuthenticatedManagerAuthenticatedRoute,
  } as any)
const AgentAuthenticatedManagerAuthenticatedGamesRoute =
  AgentAuthenticatedManagerAuthenticatedGamesRouteImport.update({
    id: '/games',
    path: '/games',
    getParentRoute: () => AgentAuthenticatedManagerAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/403': typeof R403Route
  '/': typeof AgentAuthenticatedIndexRoute
  '/agent-not-found': typeof AgentNotFoundRoute
  '/language': typeof LanguageRoute
  '/manager': typeof AgentAuthenticatedManagerAuthenticatedRouteWithChildren
  '/owner': typeof AgentAuthenticatedOwnerAuthenticatedRouteWithChildren
  '/staff': typeof AgentAuthenticatedStaffAuthenticatedRouteWithChildren
  '/user': typeof AgentAuthenticatedUserAuthenticatedRouteWithChildren
  '/manager/games': typeof AgentAuthenticatedManagerAuthenticatedGamesRoute
  '/manager/iqr': typeof AgentAuthenticatedManagerAuthenticatedIqrRoute
  '/manager/loyalty': typeof AgentAuthenticatedManagerAuthenticatedLoyaltyRoute
  '/manager/staffs': typeof AgentAuthenticatedManagerAuthenticatedStaffsRoute
  '/manager/stations': typeof AgentAuthenticatedManagerAuthenticatedStationsRoute
  '/owner/diary': typeof AgentAuthenticatedOwnerAuthenticatedDiaryRoute
  '/owner/finance': typeof AgentAuthenticatedOwnerAuthenticatedFinanceRoute
  '/owner/general': typeof AgentAuthenticatedOwnerAuthenticatedGeneralRoute
  '/owner/policy': typeof AgentAuthenticatedOwnerAuthenticatedPolicyRoute
  '/owner/system': typeof AgentAuthenticatedOwnerAuthenticatedSystemRoute
  '/staff/accounts': typeof AgentAuthenticatedStaffAuthenticatedAccountsRoute
  '/staff/order': typeof AgentAuthenticatedStaffAuthenticatedOrderRoute
  '/staff/stations': typeof AgentAuthenticatedStaffAuthenticatedStationsRoute
  '/user/device': typeof AgentAuthenticatedUserAuthenticatedDeviceRoute
  '/user/loyalty': typeof AgentAuthenticatedUserAuthenticatedLoyaltyRoute
  '/user/order': typeof AgentAuthenticatedUserAuthenticatedOrderRoute
  '/user/topup': typeof AgentAuthenticatedUserAuthenticatedTopupRoute
  '/manager/': typeof AgentAuthenticatedManagerAuthenticatedIndexRoute
  '/owner/': typeof AgentAuthenticatedOwnerAuthenticatedIndexRoute
  '/staff/': typeof AgentAuthenticatedStaffAuthenticatedIndexRoute
  '/user/': typeof AgentAuthenticatedUserAuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/403': typeof R403Route
  '/': typeof AgentAuthenticatedIndexRoute
  '/agent-not-found': typeof AgentNotFoundRoute
  '/language': typeof LanguageRoute
  '/manager/games': typeof AgentAuthenticatedManagerAuthenticatedGamesRoute
  '/manager/iqr': typeof AgentAuthenticatedManagerAuthenticatedIqrRoute
  '/manager/loyalty': typeof AgentAuthenticatedManagerAuthenticatedLoyaltyRoute
  '/manager/staffs': typeof AgentAuthenticatedManagerAuthenticatedStaffsRoute
  '/manager/stations': typeof AgentAuthenticatedManagerAuthenticatedStationsRoute
  '/owner/diary': typeof AgentAuthenticatedOwnerAuthenticatedDiaryRoute
  '/owner/finance': typeof AgentAuthenticatedOwnerAuthenticatedFinanceRoute
  '/owner/general': typeof AgentAuthenticatedOwnerAuthenticatedGeneralRoute
  '/owner/policy': typeof AgentAuthenticatedOwnerAuthenticatedPolicyRoute
  '/owner/system': typeof AgentAuthenticatedOwnerAuthenticatedSystemRoute
  '/staff/accounts': typeof AgentAuthenticatedStaffAuthenticatedAccountsRoute
  '/staff/order': typeof AgentAuthenticatedStaffAuthenticatedOrderRoute
  '/staff/stations': typeof AgentAuthenticatedStaffAuthenticatedStationsRoute
  '/user/device': typeof AgentAuthenticatedUserAuthenticatedDeviceRoute
  '/user/loyalty': typeof AgentAuthenticatedUserAuthenticatedLoyaltyRoute
  '/user/order': typeof AgentAuthenticatedUserAuthenticatedOrderRoute
  '/user/topup': typeof AgentAuthenticatedUserAuthenticatedTopupRoute
  '/manager': typeof AgentAuthenticatedManagerAuthenticatedIndexRoute
  '/owner': typeof AgentAuthenticatedOwnerAuthenticatedIndexRoute
  '/staff': typeof AgentAuthenticatedStaffAuthenticatedIndexRoute
  '/user': typeof AgentAuthenticatedUserAuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/403': typeof R403Route
  '/_agent': typeof AgentRouteWithChildren
  '/agent-not-found': typeof AgentNotFoundRoute
  '/language': typeof LanguageRoute
  '/_agent/_authenticated': typeof AgentAuthenticatedRouteWithChildren
  '/_agent/_authenticated/': typeof AgentAuthenticatedIndexRoute
  '/_agent/_authenticated/manager/_authenticated': typeof AgentAuthenticatedManagerAuthenticatedRouteWithChildren
  '/_agent/_authenticated/owner/_authenticated': typeof AgentAuthenticatedOwnerAuthenticatedRouteWithChildren
  '/_agent/_authenticated/staff/_authenticated': typeof AgentAuthenticatedStaffAuthenticatedRouteWithChildren
  '/_agent/_authenticated/user/_authenticated': typeof AgentAuthenticatedUserAuthenticatedRouteWithChildren
  '/_agent/_authenticated/manager/_authenticated/games': typeof AgentAuthenticatedManagerAuthenticatedGamesRoute
  '/_agent/_authenticated/manager/_authenticated/iqr': typeof AgentAuthenticatedManagerAuthenticatedIqrRoute
  '/_agent/_authenticated/manager/_authenticated/loyalty': typeof AgentAuthenticatedManagerAuthenticatedLoyaltyRoute
  '/_agent/_authenticated/manager/_authenticated/staffs': typeof AgentAuthenticatedManagerAuthenticatedStaffsRoute
  '/_agent/_authenticated/manager/_authenticated/stations': typeof AgentAuthenticatedManagerAuthenticatedStationsRoute
  '/_agent/_authenticated/owner/_authenticated/diary': typeof AgentAuthenticatedOwnerAuthenticatedDiaryRoute
  '/_agent/_authenticated/owner/_authenticated/finance': typeof AgentAuthenticatedOwnerAuthenticatedFinanceRoute
  '/_agent/_authenticated/owner/_authenticated/general': typeof AgentAuthenticatedOwnerAuthenticatedGeneralRoute
  '/_agent/_authenticated/owner/_authenticated/policy': typeof AgentAuthenticatedOwnerAuthenticatedPolicyRoute
  '/_agent/_authenticated/owner/_authenticated/system': typeof AgentAuthenticatedOwnerAuthenticatedSystemRoute
  '/_agent/_authenticated/staff/_authenticated/accounts': typeof AgentAuthenticatedStaffAuthenticatedAccountsRoute
  '/_agent/_authenticated/staff/_authenticated/order': typeof AgentAuthenticatedStaffAuthenticatedOrderRoute
  '/_agent/_authenticated/staff/_authenticated/stations': typeof AgentAuthenticatedStaffAuthenticatedStationsRoute
  '/_agent/_authenticated/user/_authenticated/device': typeof AgentAuthenticatedUserAuthenticatedDeviceRoute
  '/_agent/_authenticated/user/_authenticated/loyalty': typeof AgentAuthenticatedUserAuthenticatedLoyaltyRoute
  '/_agent/_authenticated/user/_authenticated/order': typeof AgentAuthenticatedUserAuthenticatedOrderRoute
  '/_agent/_authenticated/user/_authenticated/topup': typeof AgentAuthenticatedUserAuthenticatedTopupRoute
  '/_agent/_authenticated/manager/_authenticated/': typeof AgentAuthenticatedManagerAuthenticatedIndexRoute
  '/_agent/_authenticated/owner/_authenticated/': typeof AgentAuthenticatedOwnerAuthenticatedIndexRoute
  '/_agent/_authenticated/staff/_authenticated/': typeof AgentAuthenticatedStaffAuthenticatedIndexRoute
  '/_agent/_authenticated/user/_authenticated/': typeof AgentAuthenticatedUserAuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/403'
    | '/'
    | '/agent-not-found'
    | '/language'
    | '/manager'
    | '/owner'
    | '/staff'
    | '/user'
    | '/manager/games'
    | '/manager/iqr'
    | '/manager/loyalty'
    | '/manager/staffs'
    | '/manager/stations'
    | '/owner/diary'
    | '/owner/finance'
    | '/owner/general'
    | '/owner/policy'
    | '/owner/system'
    | '/staff/accounts'
    | '/staff/order'
    | '/staff/stations'
    | '/user/device'
    | '/user/loyalty'
    | '/user/order'
    | '/user/topup'
    | '/manager/'
    | '/owner/'
    | '/staff/'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/403'
    | '/'
    | '/agent-not-found'
    | '/language'
    | '/manager/games'
    | '/manager/iqr'
    | '/manager/loyalty'
    | '/manager/staffs'
    | '/manager/stations'
    | '/owner/diary'
    | '/owner/finance'
    | '/owner/general'
    | '/owner/policy'
    | '/owner/system'
    | '/staff/accounts'
    | '/staff/order'
    | '/staff/stations'
    | '/user/device'
    | '/user/loyalty'
    | '/user/order'
    | '/user/topup'
    | '/manager'
    | '/owner'
    | '/staff'
    | '/user'
  id:
    | '__root__'
    | '/403'
    | '/_agent'
    | '/agent-not-found'
    | '/language'
    | '/_agent/_authenticated'
    | '/_agent/_authenticated/'
    | '/_agent/_authenticated/manager/_authenticated'
    | '/_agent/_authenticated/owner/_authenticated'
    | '/_agent/_authenticated/staff/_authenticated'
    | '/_agent/_authenticated/user/_authenticated'
    | '/_agent/_authenticated/manager/_authenticated/games'
    | '/_agent/_authenticated/manager/_authenticated/iqr'
    | '/_agent/_authenticated/manager/_authenticated/loyalty'
    | '/_agent/_authenticated/manager/_authenticated/staffs'
    | '/_agent/_authenticated/manager/_authenticated/stations'
    | '/_agent/_authenticated/owner/_authenticated/diary'
    | '/_agent/_authenticated/owner/_authenticated/finance'
    | '/_agent/_authenticated/owner/_authenticated/general'
    | '/_agent/_authenticated/owner/_authenticated/policy'
    | '/_agent/_authenticated/owner/_authenticated/system'
    | '/_agent/_authenticated/staff/_authenticated/accounts'
    | '/_agent/_authenticated/staff/_authenticated/order'
    | '/_agent/_authenticated/staff/_authenticated/stations'
    | '/_agent/_authenticated/user/_authenticated/device'
    | '/_agent/_authenticated/user/_authenticated/loyalty'
    | '/_agent/_authenticated/user/_authenticated/order'
    | '/_agent/_authenticated/user/_authenticated/topup'
    | '/_agent/_authenticated/manager/_authenticated/'
    | '/_agent/_authenticated/owner/_authenticated/'
    | '/_agent/_authenticated/staff/_authenticated/'
    | '/_agent/_authenticated/user/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R403Route: typeof R403Route
  AgentRoute: typeof AgentRouteWithChildren
  AgentNotFoundRoute: typeof AgentNotFoundRoute
  LanguageRoute: typeof LanguageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-not-found': {
      id: '/agent-not-found'
      path: '/agent-not-found'
      fullPath: '/agent-not-found'
      preLoaderRoute: typeof AgentNotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_agent': {
      id: '/_agent'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_agent/_authenticated': {
      id: '/_agent/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AgentAuthenticatedRouteImport
      parentRoute: typeof AgentRoute
    }
    '/_agent/_authenticated/': {
      id: '/_agent/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AgentAuthenticatedIndexRouteImport
      parentRoute: typeof AgentAuthenticatedRoute
    }
    '/_agent/_authenticated/user/_authenticated': {
      id: '/_agent/_authenticated/user/_authenticated'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AgentAuthenticatedUserAuthenticatedRouteImport
      parentRoute: typeof AgentAuthenticatedRoute
    }
    '/_agent/_authenticated/staff/_authenticated': {
      id: '/_agent/_authenticated/staff/_authenticated'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AgentAuthenticatedStaffAuthenticatedRouteImport
      parentRoute: typeof AgentAuthenticatedRoute
    }
    '/_agent/_authenticated/owner/_authenticated': {
      id: '/_agent/_authenticated/owner/_authenticated'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AgentAuthenticatedOwnerAuthenticatedRouteImport
      parentRoute: typeof AgentAuthenticatedRoute
    }
    '/_agent/_authenticated/manager/_authenticated': {
      id: '/_agent/_authenticated/manager/_authenticated'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AgentAuthenticatedManagerAuthenticatedRouteImport
      parentRoute: typeof AgentAuthenticatedRoute
    }
    '/_agent/_authenticated/user/_authenticated/': {
      id: '/_agent/_authenticated/user/_authenticated/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof AgentAuthenticatedUserAuthenticatedIndexRouteImport
      parentRoute: typeof AgentAuthenticatedUserAuthenticatedRoute
    }
    '/_agent/_authenticated/staff/_authenticated/': {
      id: '/_agent/_authenticated/staff/_authenticated/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof AgentAuthenticatedStaffAuthenticatedIndexRouteImport
      parentRoute: typeof AgentAuthenticatedStaffAuthenticatedRoute
    }
    '/_agent/_authenticated/owner/_authenticated/': {
      id: '/_agent/_authenticated/owner/_authenticated/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof AgentAuthenticatedOwnerAuthenticatedIndexRouteImport
      parentRoute: typeof AgentAuthenticatedOwnerAuthenticatedRoute
    }
    '/_agent/_authenticated/manager/_authenticated/': {
      id: '/_agent/_authenticated/manager/_authenticated/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof AgentAuthenticatedManagerAuthenticatedIndexRouteImport
      parentRoute: typeof AgentAuthenticatedManagerAuthenticatedRoute
    }
    '/_agent/_authenticated/user/_authenticated/topup': {
      id: '/_agent/_authenticated/user/_authenticated/topup'
      path: '/topup'
      fullPath: '/user/topup'
      preLoaderRoute: typeof AgentAuthenticatedUserAuthenticatedTopupRouteImport
      parentRoute: typeof AgentAuthenticatedUserAuthenticatedRoute
    }
    '/_agent/_authenticated/user/_authenticated/order': {
      id: '/_agent/_authenticated/user/_authenticated/order'
      path: '/order'
      fullPath: '/user/order'
      preLoaderRoute: typeof AgentAuthenticatedUserAuthenticatedOrderRouteImport
      parentRoute: typeof AgentAuthenticatedUserAuthenticatedRoute
    }
    '/_agent/_authenticated/user/_authenticated/loyalty': {
      id: '/_agent/_authenticated/user/_authenticated/loyalty'
      path: '/loyalty'
      fullPath: '/user/loyalty'
      preLoaderRoute: typeof AgentAuthenticatedUserAuthenticatedLoyaltyRouteImport
      parentRoute: typeof AgentAuthenticatedUserAuthenticatedRoute
    }
    '/_agent/_authenticated/user/_authenticated/device': {
      id: '/_agent/_authenticated/user/_authenticated/device'
      path: '/device'
      fullPath: '/user/device'
      preLoaderRoute: typeof AgentAuthenticatedUserAuthenticatedDeviceRouteImport
      parentRoute: typeof AgentAuthenticatedUserAuthenticatedRoute
    }
    '/_agent/_authenticated/staff/_authenticated/stations': {
      id: '/_agent/_authenticated/staff/_authenticated/stations'
      path: '/stations'
      fullPath: '/staff/stations'
      preLoaderRoute: typeof AgentAuthenticatedStaffAuthenticatedStationsRouteImport
      parentRoute: typeof AgentAuthenticatedStaffAuthenticatedRoute
    }
    '/_agent/_authenticated/staff/_authenticated/order': {
      id: '/_agent/_authenticated/staff/_authenticated/order'
      path: '/order'
      fullPath: '/staff/order'
      preLoaderRoute: typeof AgentAuthenticatedStaffAuthenticatedOrderRouteImport
      parentRoute: typeof AgentAuthenticatedStaffAuthenticatedRoute
    }
    '/_agent/_authenticated/staff/_authenticated/accounts': {
      id: '/_agent/_authenticated/staff/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/staff/accounts'
      preLoaderRoute: typeof AgentAuthenticatedStaffAuthenticatedAccountsRouteImport
      parentRoute: typeof AgentAuthenticatedStaffAuthenticatedRoute
    }
    '/_agent/_authenticated/owner/_authenticated/system': {
      id: '/_agent/_authenticated/owner/_authenticated/system'
      path: '/system'
      fullPath: '/owner/system'
      preLoaderRoute: typeof AgentAuthenticatedOwnerAuthenticatedSystemRouteImport
      parentRoute: typeof AgentAuthenticatedOwnerAuthenticatedRoute
    }
    '/_agent/_authenticated/owner/_authenticated/policy': {
      id: '/_agent/_authenticated/owner/_authenticated/policy'
      path: '/policy'
      fullPath: '/owner/policy'
      preLoaderRoute: typeof AgentAuthenticatedOwnerAuthenticatedPolicyRouteImport
      parentRoute: typeof AgentAuthenticatedOwnerAuthenticatedRoute
    }
    '/_agent/_authenticated/owner/_authenticated/general': {
      id: '/_agent/_authenticated/owner/_authenticated/general'
      path: '/general'
      fullPath: '/owner/general'
      preLoaderRoute: typeof AgentAuthenticatedOwnerAuthenticatedGeneralRouteImport
      parentRoute: typeof AgentAuthenticatedOwnerAuthenticatedRoute
    }
    '/_agent/_authenticated/owner/_authenticated/finance': {
      id: '/_agent/_authenticated/owner/_authenticated/finance'
      path: '/finance'
      fullPath: '/owner/finance'
      preLoaderRoute: typeof AgentAuthenticatedOwnerAuthenticatedFinanceRouteImport
      parentRoute: typeof AgentAuthenticatedOwnerAuthenticatedRoute
    }
    '/_agent/_authenticated/owner/_authenticated/diary': {
      id: '/_agent/_authenticated/owner/_authenticated/diary'
      path: '/diary'
      fullPath: '/owner/diary'
      preLoaderRoute: typeof AgentAuthenticatedOwnerAuthenticatedDiaryRouteImport
      parentRoute: typeof AgentAuthenticatedOwnerAuthenticatedRoute
    }
    '/_agent/_authenticated/manager/_authenticated/stations': {
      id: '/_agent/_authenticated/manager/_authenticated/stations'
      path: '/stations'
      fullPath: '/manager/stations'
      preLoaderRoute: typeof AgentAuthenticatedManagerAuthenticatedStationsRouteImport
      parentRoute: typeof AgentAuthenticatedManagerAuthenticatedRoute
    }
    '/_agent/_authenticated/manager/_authenticated/staffs': {
      id: '/_agent/_authenticated/manager/_authenticated/staffs'
      path: '/staffs'
      fullPath: '/manager/staffs'
      preLoaderRoute: typeof AgentAuthenticatedManagerAuthenticatedStaffsRouteImport
      parentRoute: typeof AgentAuthenticatedManagerAuthenticatedRoute
    }
    '/_agent/_authenticated/manager/_authenticated/loyalty': {
      id: '/_agent/_authenticated/manager/_authenticated/loyalty'
      path: '/loyalty'
      fullPath: '/manager/loyalty'
      preLoaderRoute: typeof AgentAuthenticatedManagerAuthenticatedLoyaltyRouteImport
      parentRoute: typeof AgentAuthenticatedManagerAuthenticatedRoute
    }
    '/_agent/_authenticated/manager/_authenticated/iqr': {
      id: '/_agent/_authenticated/manager/_authenticated/iqr'
      path: '/iqr'
      fullPath: '/manager/iqr'
      preLoaderRoute: typeof AgentAuthenticatedManagerAuthenticatedIqrRouteImport
      parentRoute: typeof AgentAuthenticatedManagerAuthenticatedRoute
    }
    '/_agent/_authenticated/manager/_authenticated/games': {
      id: '/_agent/_authenticated/manager/_authenticated/games'
      path: '/games'
      fullPath: '/manager/games'
      preLoaderRoute: typeof AgentAuthenticatedManagerAuthenticatedGamesRouteImport
      parentRoute: typeof AgentAuthenticatedManagerAuthenticatedRoute
    }
  }
}

interface AgentAuthenticatedManagerAuthenticatedRouteChildren {
  AgentAuthenticatedManagerAuthenticatedGamesRoute: typeof AgentAuthenticatedManagerAuthenticatedGamesRoute
  AgentAuthenticatedManagerAuthenticatedIqrRoute: typeof AgentAuthenticatedManagerAuthenticatedIqrRoute
  AgentAuthenticatedManagerAuthenticatedLoyaltyRoute: typeof AgentAuthenticatedManagerAuthenticatedLoyaltyRoute
  AgentAuthenticatedManagerAuthenticatedStaffsRoute: typeof AgentAuthenticatedManagerAuthenticatedStaffsRoute
  AgentAuthenticatedManagerAuthenticatedStationsRoute: typeof AgentAuthenticatedManagerAuthenticatedStationsRoute
  AgentAuthenticatedManagerAuthenticatedIndexRoute: typeof AgentAuthenticatedManagerAuthenticatedIndexRoute
}

const AgentAuthenticatedManagerAuthenticatedRouteChildren: AgentAuthenticatedManagerAuthenticatedRouteChildren =
  {
    AgentAuthenticatedManagerAuthenticatedGamesRoute:
      AgentAuthenticatedManagerAuthenticatedGamesRoute,
    AgentAuthenticatedManagerAuthenticatedIqrRoute:
      AgentAuthenticatedManagerAuthenticatedIqrRoute,
    AgentAuthenticatedManagerAuthenticatedLoyaltyRoute:
      AgentAuthenticatedManagerAuthenticatedLoyaltyRoute,
    AgentAuthenticatedManagerAuthenticatedStaffsRoute:
      AgentAuthenticatedManagerAuthenticatedStaffsRoute,
    AgentAuthenticatedManagerAuthenticatedStationsRoute:
      AgentAuthenticatedManagerAuthenticatedStationsRoute,
    AgentAuthenticatedManagerAuthenticatedIndexRoute:
      AgentAuthenticatedManagerAuthenticatedIndexRoute,
  }

const AgentAuthenticatedManagerAuthenticatedRouteWithChildren =
  AgentAuthenticatedManagerAuthenticatedRoute._addFileChildren(
    AgentAuthenticatedManagerAuthenticatedRouteChildren,
  )

interface AgentAuthenticatedOwnerAuthenticatedRouteChildren {
  AgentAuthenticatedOwnerAuthenticatedDiaryRoute: typeof AgentAuthenticatedOwnerAuthenticatedDiaryRoute
  AgentAuthenticatedOwnerAuthenticatedFinanceRoute: typeof AgentAuthenticatedOwnerAuthenticatedFinanceRoute
  AgentAuthenticatedOwnerAuthenticatedGeneralRoute: typeof AgentAuthenticatedOwnerAuthenticatedGeneralRoute
  AgentAuthenticatedOwnerAuthenticatedPolicyRoute: typeof AgentAuthenticatedOwnerAuthenticatedPolicyRoute
  AgentAuthenticatedOwnerAuthenticatedSystemRoute: typeof AgentAuthenticatedOwnerAuthenticatedSystemRoute
  AgentAuthenticatedOwnerAuthenticatedIndexRoute: typeof AgentAuthenticatedOwnerAuthenticatedIndexRoute
}

const AgentAuthenticatedOwnerAuthenticatedRouteChildren: AgentAuthenticatedOwnerAuthenticatedRouteChildren =
  {
    AgentAuthenticatedOwnerAuthenticatedDiaryRoute:
      AgentAuthenticatedOwnerAuthenticatedDiaryRoute,
    AgentAuthenticatedOwnerAuthenticatedFinanceRoute:
      AgentAuthenticatedOwnerAuthenticatedFinanceRoute,
    AgentAuthenticatedOwnerAuthenticatedGeneralRoute:
      AgentAuthenticatedOwnerAuthenticatedGeneralRoute,
    AgentAuthenticatedOwnerAuthenticatedPolicyRoute:
      AgentAuthenticatedOwnerAuthenticatedPolicyRoute,
    AgentAuthenticatedOwnerAuthenticatedSystemRoute:
      AgentAuthenticatedOwnerAuthenticatedSystemRoute,
    AgentAuthenticatedOwnerAuthenticatedIndexRoute:
      AgentAuthenticatedOwnerAuthenticatedIndexRoute,
  }

const AgentAuthenticatedOwnerAuthenticatedRouteWithChildren =
  AgentAuthenticatedOwnerAuthenticatedRoute._addFileChildren(
    AgentAuthenticatedOwnerAuthenticatedRouteChildren,
  )

interface AgentAuthenticatedStaffAuthenticatedRouteChildren {
  AgentAuthenticatedStaffAuthenticatedAccountsRoute: typeof AgentAuthenticatedStaffAuthenticatedAccountsRoute
  AgentAuthenticatedStaffAuthenticatedOrderRoute: typeof AgentAuthenticatedStaffAuthenticatedOrderRoute
  AgentAuthenticatedStaffAuthenticatedStationsRoute: typeof AgentAuthenticatedStaffAuthenticatedStationsRoute
  AgentAuthenticatedStaffAuthenticatedIndexRoute: typeof AgentAuthenticatedStaffAuthenticatedIndexRoute
}

const AgentAuthenticatedStaffAuthenticatedRouteChildren: AgentAuthenticatedStaffAuthenticatedRouteChildren =
  {
    AgentAuthenticatedStaffAuthenticatedAccountsRoute:
      AgentAuthenticatedStaffAuthenticatedAccountsRoute,
    AgentAuthenticatedStaffAuthenticatedOrderRoute:
      AgentAuthenticatedStaffAuthenticatedOrderRoute,
    AgentAuthenticatedStaffAuthenticatedStationsRoute:
      AgentAuthenticatedStaffAuthenticatedStationsRoute,
    AgentAuthenticatedStaffAuthenticatedIndexRoute:
      AgentAuthenticatedStaffAuthenticatedIndexRoute,
  }

const AgentAuthenticatedStaffAuthenticatedRouteWithChildren =
  AgentAuthenticatedStaffAuthenticatedRoute._addFileChildren(
    AgentAuthenticatedStaffAuthenticatedRouteChildren,
  )

interface AgentAuthenticatedUserAuthenticatedRouteChildren {
  AgentAuthenticatedUserAuthenticatedDeviceRoute: typeof AgentAuthenticatedUserAuthenticatedDeviceRoute
  AgentAuthenticatedUserAuthenticatedLoyaltyRoute: typeof AgentAuthenticatedUserAuthenticatedLoyaltyRoute
  AgentAuthenticatedUserAuthenticatedOrderRoute: typeof AgentAuthenticatedUserAuthenticatedOrderRoute
  AgentAuthenticatedUserAuthenticatedTopupRoute: typeof AgentAuthenticatedUserAuthenticatedTopupRoute
  AgentAuthenticatedUserAuthenticatedIndexRoute: typeof AgentAuthenticatedUserAuthenticatedIndexRoute
}

const AgentAuthenticatedUserAuthenticatedRouteChildren: AgentAuthenticatedUserAuthenticatedRouteChildren =
  {
    AgentAuthenticatedUserAuthenticatedDeviceRoute:
      AgentAuthenticatedUserAuthenticatedDeviceRoute,
    AgentAuthenticatedUserAuthenticatedLoyaltyRoute:
      AgentAuthenticatedUserAuthenticatedLoyaltyRoute,
    AgentAuthenticatedUserAuthenticatedOrderRoute:
      AgentAuthenticatedUserAuthenticatedOrderRoute,
    AgentAuthenticatedUserAuthenticatedTopupRoute:
      AgentAuthenticatedUserAuthenticatedTopupRoute,
    AgentAuthenticatedUserAuthenticatedIndexRoute:
      AgentAuthenticatedUserAuthenticatedIndexRoute,
  }

const AgentAuthenticatedUserAuthenticatedRouteWithChildren =
  AgentAuthenticatedUserAuthenticatedRoute._addFileChildren(
    AgentAuthenticatedUserAuthenticatedRouteChildren,
  )

interface AgentAuthenticatedRouteChildren {
  AgentAuthenticatedIndexRoute: typeof AgentAuthenticatedIndexRoute
  AgentAuthenticatedManagerAuthenticatedRoute: typeof AgentAuthenticatedManagerAuthenticatedRouteWithChildren
  AgentAuthenticatedOwnerAuthenticatedRoute: typeof AgentAuthenticatedOwnerAuthenticatedRouteWithChildren
  AgentAuthenticatedStaffAuthenticatedRoute: typeof AgentAuthenticatedStaffAuthenticatedRouteWithChildren
  AgentAuthenticatedUserAuthenticatedRoute: typeof AgentAuthenticatedUserAuthenticatedRouteWithChildren
}

const AgentAuthenticatedRouteChildren: AgentAuthenticatedRouteChildren = {
  AgentAuthenticatedIndexRoute: AgentAuthenticatedIndexRoute,
  AgentAuthenticatedManagerAuthenticatedRoute:
    AgentAuthenticatedManagerAuthenticatedRouteWithChildren,
  AgentAuthenticatedOwnerAuthenticatedRoute:
    AgentAuthenticatedOwnerAuthenticatedRouteWithChildren,
  AgentAuthenticatedStaffAuthenticatedRoute:
    AgentAuthenticatedStaffAuthenticatedRouteWithChildren,
  AgentAuthenticatedUserAuthenticatedRoute:
    AgentAuthenticatedUserAuthenticatedRouteWithChildren,
}

const AgentAuthenticatedRouteWithChildren =
  AgentAuthenticatedRoute._addFileChildren(AgentAuthenticatedRouteChildren)

interface AgentRouteChildren {
  AgentAuthenticatedRoute: typeof AgentAuthenticatedRouteWithChildren
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentAuthenticatedRoute: AgentAuthenticatedRouteWithChildren,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  R403Route: R403Route,
  AgentRoute: AgentRouteWithChildren,
  AgentNotFoundRoute: AgentNotFoundRoute,
  LanguageRoute: LanguageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
