export {}
declare global {
  type BCMethods = { file: BCFileMethods }

  type BCFileMethods = {
    UPGRADE_INTERFACE_VERSION: [undefined, any]
    addOwner: [{ _owner: any }, void]
    addStorageServer: [{ _server: any }, void]
    addValidator: [{ _validator: any }, void]
    addWhitelist: [{ fileKey: any; users: any[] }, void]
    calculatePrice: [{ numChunks: any }, any]
    confirmFileActive: [{ fileKey: any }, void]
    confirmServerDownload: [{ downloadKey: any }, void]
    deleteFile: [{ fileKey: any }, void]
    downloadFile: [{ fileKey: any; start: any; limit: any }, void]
    getContractBalance: [undefined, any]
    getDownloadSessionInfo: [{ downloadKey: any }, BCDownloadSession]
    getFileInfo: [{ fileKey: any }, BCInfo]
    getFileKeyFromName: [{ names: any[] }, any[]]
    getFileProgress: [{ fileKey: any }, BCFileProgress]
    getFilesInfo: [{ fileKeys: any[] }, { infos: BCInfo[] }]
    getOwnerList: [undefined, any[]]
    getRustServerAddresses: [undefined, any[]]
    getStorageServerList: [undefined, any[]]
    getValidatorList: [undefined, any[]]
    getWhitelist: [{ fileKey: any }, any[]]
    initialize: [undefined, void]
    isOwner: [{ _address: any }, boolean]
    isPublicFile: [{ '': any }, boolean]
    isStorageServer: [{ _address: any }, boolean]
    isValidator: [{ _address: any }, boolean]
    mDownloadKeyToSession: [{ '': any }, { fileKey: any; user: any; isConfirmed: boolean }]
    mKeyToFileInfo: [{ '': any }, { info: BCInfo; progress: BCFileProgress }]
    mNameToFileKey: [{ '': any }, any]
    ownerList: [{ '': any }, any]
    owners: [{ '': any }, boolean]
    payForDownload: [{ fileKey: any; downloadTimes: any }, void]
    pricePerChunk: [undefined, any]
    proxiableUUID: [undefined, any]
    pushFileInfo: [{ info: BCInfo }, { fileKey: any }]
    removeOwner: [{ _owner: any }, void]
    removeStorageServer: [{ _server: any }, void]
    removeValidator: [{ _validator: any }, void]
    renewTime: [{ fileKey: any; _newExpireTime: any }, void]
    rustServerAddresses: [{ '': any }, any]
    service: [undefined, any]
    setPricePerChunk: [{ _newPrice: any }, void]
    setPublicStatus: [{ fileKey: any; status: boolean }, void]
    setRustServerAddresses: [{ _addresses: any[] }, void]
    storageServerList: [{ '': any }, any]
    storageServers: [{ '': any }, boolean]
    upgradeToAndCall: [{ newImplementation: any; data: unknown }, void]
    uploadChunk: [{ fileKey: any; chunkData: unknown; chunkIndex: any; merkleProof: any[] }, void]
    validatorList: [{ '': any }, any]
    validators: [{ '': any }, boolean]
    withdrawAmount: [{ amount: any }, void]
  }
}
