import type * as Structs from '../structs'
export type FileMehods = {
  UPGRADE_INTERFACE_VERSION: [null, string]
  addOwner: [{ _owner: string }, void]
  addStorageServer: [{ _server: string }, void]
  addValidator: [{ _validator: string }, void]
  addWhitelist: [{ fileKey: string; users: string[] }, void]
  calculatePrice: [{ numChunks: number }, number]
  confirmFileActive: [{ fileKey: string }, void]
  confirmServerDownload: [{ downloadKey: string }, void]
  deleteFile: [{ fileKey: string }, void]
  downloadFile: [{ fileKey: string; start: number; limit: number }, void]
  getContractBalance: [null, number]
  getDownloadSessionInfo: [{ downloadKey: string }, Structs.BCDownloadSession]
  getFileInfo: [{ fileKey: string }, Structs.BCInfo]
  getFileKeyFromName: [{ names: string[] }, string[]]
  getFileProgress: [{ fileKey: string }, Structs.BCFileProgress]
  getFilesInfo: [{ fileKeys: string[] }, { infos: Structs.BCInfo[] }]
  getOwnerList: [null, string[]]
  getRustServerAddresses: [null, string[]]
  getStorageServerList: [null, string[]]
  getValidatorList: [null, string[]]
  getWhitelist: [{ fileKey: string }, string[]]
  initialize: [null, void]
  isOwner: [{ _address: string }, boolean]
  isPublicFile: [{ '': string }, boolean]
  isStorageServer: [{ _address: string }, boolean]
  isValidator: [{ _address: string }, boolean]
  mDownloadKeyToSession: [{ '': string }, { fileKey: string; user: string; isConfirmed: boolean }]
  mKeyToFileInfo: [{ '': string }, { info: Structs.BCInfo; progress: Structs.BCFileProgress }]
  mNameToFileKey: [{ '': string }, string]
  ownerList: [{ '': number }, string]
  owners: [{ '': string }, boolean]
  payForDownload: [{ fileKey: string; downloadTimes: number }, void]
  pricePerChunk: [null, number]
  proxiableUUID: [null, string]
  pushFileInfo: [{ info: Structs.BCInfo }, { fileKey: string }]
  removeOwner: [{ _owner: string }, void]
  removeStorageServer: [{ _server: string }, void]
  removeValidator: [{ _validator: string }, void]
  renewTime: [{ fileKey: string; _newExpireTime: number }, void]
  rustServerAddresses: [{ '': number }, string]
  service: [null, string]
  setPricePerChunk: [{ _newPrice: number }, void]
  setPublicStatus: [{ fileKey: string; status: boolean }, void]
  setRustServerAddresses: [{ _addresses: string[] }, void]
  storageServerList: [{ '': number }, string]
  storageServers: [{ '': string }, boolean]
  upgradeToAndCall: [{ newImplementation: string; data: string }, void]
  uploadChunk: [
    { fileKey: string; chunkData: string; chunkIndex: number; merkleProof: string[] },
    void
  ]
  validatorList: [{ '': number }, string]
  validators: [{ '': string }, boolean]
  withdrawAmount: [{ amount: number }, void]
}
