/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletsWindowRouteImport } from './routes/wallets-window'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as TestRouteImport } from './routes/test'
import { Route as MeetingRouteImport } from './routes/meeting'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedP2pIdRouteImport } from './routes/_authenticated/p2p.$id'
import { Route as AuthenticatedGroupIdRouteImport } from './routes/_authenticated/group.$id'

const WalletsWindowRoute = WalletsWindowRouteImport.update({
  id: '/wallets-window',
  path: '/wallets-window',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingRoute = MeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedP2pIdRoute = AuthenticatedP2pIdRouteImport.update({
  id: '/p2p/$id',
  path: '/p2p/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGroupIdRoute = AuthenticatedGroupIdRouteImport.update({
  id: '/group/$id',
  path: '/group/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/meeting': typeof MeetingRoute
  '/test': typeof TestRoute
  '/wallets': typeof WalletsRoute
  '/wallets-window': typeof WalletsWindowRoute
  '/group/$id': typeof AuthenticatedGroupIdRoute
  '/p2p/$id': typeof AuthenticatedP2pIdRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/meeting': typeof MeetingRoute
  '/test': typeof TestRoute
  '/wallets': typeof WalletsRoute
  '/wallets-window': typeof WalletsWindowRoute
  '/': typeof AuthenticatedIndexRoute
  '/group/$id': typeof AuthenticatedGroupIdRoute
  '/p2p/$id': typeof AuthenticatedP2pIdRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/meeting': typeof MeetingRoute
  '/test': typeof TestRoute
  '/wallets': typeof WalletsRoute
  '/wallets-window': typeof WalletsWindowRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/group/$id': typeof AuthenticatedGroupIdRoute
  '/_authenticated/p2p/$id': typeof AuthenticatedP2pIdRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/meeting'
    | '/test'
    | '/wallets'
    | '/wallets-window'
    | '/group/$id'
    | '/p2p/$id'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/meeting'
    | '/test'
    | '/wallets'
    | '/wallets-window'
    | '/'
    | '/group/$id'
    | '/p2p/$id'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/meeting'
    | '/test'
    | '/wallets'
    | '/wallets-window'
    | '/_authenticated/'
    | '/_authenticated/group/$id'
    | '/_authenticated/p2p/$id'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  MeetingRoute: typeof MeetingRoute
  TestRoute: typeof TestRoute
  WalletsRoute: typeof WalletsRoute
  WalletsWindowRoute: typeof WalletsWindowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallets-window': {
      id: '/wallets-window'
      path: '/wallets-window'
      fullPath: '/wallets-window'
      preLoaderRoute: typeof WalletsWindowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting': {
      id: '/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof MeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/p2p/$id': {
      id: '/_authenticated/p2p/$id'
      path: '/p2p/$id'
      fullPath: '/p2p/$id'
      preLoaderRoute: typeof AuthenticatedP2pIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/group/$id': {
      id: '/_authenticated/group/$id'
      path: '/group/$id'
      fullPath: '/group/$id'
      preLoaderRoute: typeof AuthenticatedGroupIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedGroupIdRoute: typeof AuthenticatedGroupIdRoute
  AuthenticatedP2pIdRoute: typeof AuthenticatedP2pIdRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedGroupIdRoute: AuthenticatedGroupIdRoute,
  AuthenticatedP2pIdRoute: AuthenticatedP2pIdRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  MeetingRoute: MeetingRoute,
  TestRoute: TestRoute,
  WalletsRoute: WalletsRoute,
  WalletsWindowRoute: WalletsWindowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
