/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as SetupMeetingRouteImport } from './routes/setup-meeting'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as CallRouteImport } from './routes/call'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedP2pIdRouteImport } from './routes/_authenticated/p2p.$id'
import { Route as AuthenticatedTypeIdRouteImport } from './routes/_authenticated/$type.$id'
import { Route as AuthenticatedDetailTypeIdRouteImport } from './routes/_authenticated/detail.$type.$id'

const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupMeetingRoute = SetupMeetingRouteImport.update({
  id: '/setup-meeting',
  path: '/setup-meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRoute = CallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedP2pIdRoute = AuthenticatedP2pIdRouteImport.update({
  id: '/p2p/$id',
  path: '/p2p/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTypeIdRoute = AuthenticatedTypeIdRouteImport.update({
  id: '/$type/$id',
  path: '/$type/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDetailTypeIdRoute =
  AuthenticatedDetailTypeIdRouteImport.update({
    id: '/detail/$type/$id',
    path: '/detail/$type/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/call': typeof CallRoute
  '/error': typeof ErrorRoute
  '/setup-meeting': typeof SetupMeetingRoute
  '/wallets': typeof WalletsRoute
  '/$type/$id': typeof AuthenticatedTypeIdRoute
  '/p2p/$id': typeof AuthenticatedP2pIdRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/detail/$type/$id': typeof AuthenticatedDetailTypeIdRoute
}
export interface FileRoutesByTo {
  '/call': typeof CallRoute
  '/error': typeof ErrorRoute
  '/setup-meeting': typeof SetupMeetingRoute
  '/wallets': typeof WalletsRoute
  '/': typeof AuthenticatedIndexRoute
  '/$type/$id': typeof AuthenticatedTypeIdRoute
  '/p2p/$id': typeof AuthenticatedP2pIdRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/detail/$type/$id': typeof AuthenticatedDetailTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/call': typeof CallRoute
  '/error': typeof ErrorRoute
  '/setup-meeting': typeof SetupMeetingRoute
  '/wallets': typeof WalletsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$type/$id': typeof AuthenticatedTypeIdRoute
  '/_authenticated/p2p/$id': typeof AuthenticatedP2pIdRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/detail/$type/$id': typeof AuthenticatedDetailTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/call'
    | '/error'
    | '/setup-meeting'
    | '/wallets'
    | '/$type/$id'
    | '/p2p/$id'
    | '/settings/notifications'
    | '/settings/'
    | '/detail/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/call'
    | '/error'
    | '/setup-meeting'
    | '/wallets'
    | '/'
    | '/$type/$id'
    | '/p2p/$id'
    | '/settings/notifications'
    | '/settings'
    | '/detail/$type/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/call'
    | '/error'
    | '/setup-meeting'
    | '/wallets'
    | '/_authenticated/'
    | '/_authenticated/$type/$id'
    | '/_authenticated/p2p/$id'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/'
    | '/_authenticated/detail/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallRoute: typeof CallRoute
  ErrorRoute: typeof ErrorRoute
  SetupMeetingRoute: typeof SetupMeetingRoute
  WalletsRoute: typeof WalletsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-meeting': {
      id: '/setup-meeting'
      path: '/setup-meeting'
      fullPath: '/setup-meeting'
      preLoaderRoute: typeof SetupMeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call': {
      id: '/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof CallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/p2p/$id': {
      id: '/_authenticated/p2p/$id'
      path: '/p2p/$id'
      fullPath: '/p2p/$id'
      preLoaderRoute: typeof AuthenticatedP2pIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$type/$id': {
      id: '/_authenticated/$type/$id'
      path: '/$type/$id'
      fullPath: '/$type/$id'
      preLoaderRoute: typeof AuthenticatedTypeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/detail/$type/$id': {
      id: '/_authenticated/detail/$type/$id'
      path: '/detail/$type/$id'
      fullPath: '/detail/$type/$id'
      preLoaderRoute: typeof AuthenticatedDetailTypeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedTypeIdRoute: typeof AuthenticatedTypeIdRoute
  AuthenticatedP2pIdRoute: typeof AuthenticatedP2pIdRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedDetailTypeIdRoute: typeof AuthenticatedDetailTypeIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedTypeIdRoute: AuthenticatedTypeIdRoute,
  AuthenticatedP2pIdRoute: AuthenticatedP2pIdRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedDetailTypeIdRoute: AuthenticatedDetailTypeIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallRoute: CallRoute,
  ErrorRoute: ErrorRoute,
  SetupMeetingRoute: SetupMeetingRoute,
  WalletsRoute: WalletsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
