export { detectNameFromWalletName } from './detect-name-from-wallet-name'
export { generateAvailableUsername, generateUsernameFromWalletName } from './username-generator'
export { getAvatarFallback } from './get-avatar-fallback'
export { getTelegramGradient } from './get-gradient-from-name'
export { formatUpdatedAt } from './date-fns'
