/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutManagerProfileRouteImport } from './routes/_layout/manager-profile'
import { Route as LayoutProfileIdRouteImport } from './routes/_layout/profile.$id'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute
} as any)
const LayoutManagerProfileRoute = LayoutManagerProfileRouteImport.update({
  id: '/manager-profile',
  path: '/manager-profile',
  getParentRoute: () => LayoutRoute
} as any)
const LayoutProfileIdRoute = LayoutProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => LayoutRoute
} as any)

export interface FileRoutesByFullPath {
  '/manager-profile': typeof LayoutManagerProfileRoute
  '/': typeof LayoutIndexRoute
  '/profile/$id': typeof LayoutProfileIdRoute
}
export interface FileRoutesByTo {
  '/manager-profile': typeof LayoutManagerProfileRoute
  '/': typeof LayoutIndexRoute
  '/profile/$id': typeof LayoutProfileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/manager-profile': typeof LayoutManagerProfileRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/profile/$id': typeof LayoutProfileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/manager-profile' | '/' | '/profile/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/manager-profile' | '/' | '/profile/$id'
  id: '__root__' | '/_layout' | '/_layout/manager-profile' | '/_layout/' | '/_layout/profile/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/manager-profile': {
      id: '/_layout/manager-profile'
      path: '/manager-profile'
      fullPath: '/manager-profile'
      preLoaderRoute: typeof LayoutManagerProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile/$id': {
      id: '/_layout/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof LayoutProfileIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutManagerProfileRoute: typeof LayoutManagerProfileRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProfileIdRoute: typeof LayoutProfileIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutManagerProfileRoute: LayoutManagerProfileRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProfileIdRoute: LayoutProfileIdRoute
}

const LayoutRouteWithChildren = LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
