/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutProfileDetailRouteImport } from './routes/_layout/profile-detail'
import { Route as LayoutManagerProfileRouteImport } from './routes/_layout/manager-profile'
import { Route as LayoutNewProfileIndexRouteImport } from './routes/_layout/new-profile/index'
import { Route as LayoutNewProfileCreateIndexRouteImport } from './routes/_layout/new-profile/create/index'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute
} as any)
const LayoutProfileDetailRoute = LayoutProfileDetailRouteImport.update({
  id: '/profile-detail',
  path: '/profile-detail',
  getParentRoute: () => LayoutRoute
} as any)
const LayoutManagerProfileRoute = LayoutManagerProfileRouteImport.update({
  id: '/manager-profile',
  path: '/manager-profile',
  getParentRoute: () => LayoutRoute
} as any)
const LayoutNewProfileIndexRoute = LayoutNewProfileIndexRouteImport.update({
  id: '/new-profile/',
  path: '/new-profile/',
  getParentRoute: () => LayoutRoute
} as any)
const LayoutNewProfileCreateIndexRoute = LayoutNewProfileCreateIndexRouteImport.update({
  id: '/new-profile/create/',
  path: '/new-profile/create/',
  getParentRoute: () => LayoutRoute
} as any)

export interface FileRoutesByFullPath {
  '/manager-profile': typeof LayoutManagerProfileRoute
  '/profile-detail': typeof LayoutProfileDetailRoute
  '/': typeof LayoutIndexRoute
  '/new-profile': typeof LayoutNewProfileIndexRoute
  '/new-profile/create': typeof LayoutNewProfileCreateIndexRoute
}
export interface FileRoutesByTo {
  '/manager-profile': typeof LayoutManagerProfileRoute
  '/profile-detail': typeof LayoutProfileDetailRoute
  '/': typeof LayoutIndexRoute
  '/new-profile': typeof LayoutNewProfileIndexRoute
  '/new-profile/create': typeof LayoutNewProfileCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/manager-profile': typeof LayoutManagerProfileRoute
  '/_layout/profile-detail': typeof LayoutProfileDetailRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/new-profile/': typeof LayoutNewProfileIndexRoute
  '/_layout/new-profile/create/': typeof LayoutNewProfileCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/manager-profile' | '/profile-detail' | '/' | '/new-profile' | '/new-profile/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/manager-profile' | '/profile-detail' | '/' | '/new-profile' | '/new-profile/create'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/manager-profile'
    | '/_layout/profile-detail'
    | '/_layout/'
    | '/_layout/new-profile/'
    | '/_layout/new-profile/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile-detail': {
      id: '/_layout/profile-detail'
      path: '/profile-detail'
      fullPath: '/profile-detail'
      preLoaderRoute: typeof LayoutProfileDetailRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/manager-profile': {
      id: '/_layout/manager-profile'
      path: '/manager-profile'
      fullPath: '/manager-profile'
      preLoaderRoute: typeof LayoutManagerProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/new-profile/': {
      id: '/_layout/new-profile/'
      path: '/new-profile'
      fullPath: '/new-profile'
      preLoaderRoute: typeof LayoutNewProfileIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/new-profile/create/': {
      id: '/_layout/new-profile/create/'
      path: '/new-profile/create'
      fullPath: '/new-profile/create'
      preLoaderRoute: typeof LayoutNewProfileCreateIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutManagerProfileRoute: typeof LayoutManagerProfileRoute
  LayoutProfileDetailRoute: typeof LayoutProfileDetailRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutNewProfileIndexRoute: typeof LayoutNewProfileIndexRoute
  LayoutNewProfileCreateIndexRoute: typeof LayoutNewProfileCreateIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutManagerProfileRoute: LayoutManagerProfileRoute,
  LayoutProfileDetailRoute: LayoutProfileDetailRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutNewProfileIndexRoute: LayoutNewProfileIndexRoute,
  LayoutNewProfileCreateIndexRoute: LayoutNewProfileCreateIndexRoute
}

const LayoutRouteWithChildren = LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
